base_dir: __base_dir__
steps:
  - command: "cfy local init --blueprint-path blueprint.yaml --inputs '{\"webserver_port\" : \"__port__\", \"host_ip\":\"localhost\" }'"
    intro: >
      ======================================================

      WELCOME TO CLOUDIFY TUTORIAL

      ======================================================


      first we want to locally initialize the blueprint.

      to do so we need to run the command:


             {0}


      this will setup a local environment for us to run the blueprint
  - command: cfy local execute --workflow install
    intro: >




      Now that we have initialized the blueprint it's time to install it.


      to install the blueprint run the command:


             {0}


      and follow the logs until it is completed
  - command: exit
    intro: ''