---
- hosts: {{ ctx.node.name }}
  remote_user: ubuntu
  vars_files:
    - ./default.yml

  tasks:
    - name: Define "sys_update" var.
      shell: 'Ansible veriable sys_update'
      register: sys_update

    - name: Define "deploy" var.
      shell: 'Ansible veriable deploy'
      register: deploy_code

    - name: Run apt-get update.
      sudo: yes
      apt: update_cache=yes
      when: ansible_pkg_mgr == "apt" and sys_update.stdout == "True"

    - name: Install dependencies packages.
      sudo: yes
      apt: name=Ansible-items state=present
      with_items:
         - build-essential
         - libssl-dev
         - libffi-dev
         - python-pip
         - python-dev
         - unzip
         - git
         - wget
         - npm
      when: ansible_pkg_mgr == "apt"

    - name: Check if cloudify-interactive-tutorial folder exsist for clone.
      stat: path=/home/ubuntu/cloudify-interactive-tutorial
      register: tutorial_clone_status

    - name: Clone the cloudify-interactive-tutorial repo git.
      git: repo=https://github.com/cloudify-cosmo/cloudify-interactive-tutorial.git dest=/home/ubuntu/cloudify-interactive-tutorial clone=yes update=no
      when: tutorial_clone_status.stat.exists == False

    - name: Check if simple-python-webserver-blueprint folder exsist for clone.
      stat: path=/home/ubuntu/simple-python-webserver-blueprint
      register: blueprint_clone_status

    - name: Clone the simple-python-webserver-blueprint repo git.
      git: repo=https://github.com/cloudify-examples/simple-python-webserver-blueprint.git dest=/home/ubuntu/simple-python-webserver-blueprint clone=yes update=no
      when: blueprint_clone_status.stat.exists == False

    - name: Create nodejs directory.
      sudo: yes
      file: path=/opt/nodejs state=directory mode=0755

    - name: Download & extarct the node file.
      sudo: yes
      unarchive: src="https://nodejs.org/dist/v4.2.1/node-v4.2.1-linux-x64.tar.gz" dest=/opt/nodejs copy=no
      when: deploy_code.stdout == "False"

    - name: Deploy the cloudify-interactive-tutorial repo git.
      git: repo=https://github.com/cloudify-cosmo/cloudify-interactive-tutorial.git dest=/home/ubuntu/cloudify-interactive-tutorial clone=no update=yes
      when: tutorial_clone_status.stat.exists == True and deploy_code.stdout == "True"

    - name: Install interactive tutorial.
      sudo: yes
      shell: 'npm install -g cloudify-cosmo/cloudify-interactive-tutorial'
      when: deploy_code.stdout == "False"

    - name: Create symlink to node.
      sudo: yes
      file: src=/opt/nodejs/node-v4.2.1-linux-x64/bin/node dest=/bin/node state=link

    - name: Install pip package.
      sudo: yes
      pip: name=Ansible-items
      with_items:
         - cloudify
         - butterfly==2.0.0

    - name: Activate cfy.
      shell: 'activate_cfy_bash_completion'

    - name: Define "ext_ip" var.
      shell: dig +short myip.opendns.com @resolver1.opendns.com
      register: ext_ip

    - name: Find butterfly pid.
      shell: pgrep ^butterfly
      register: butterfly_PID
      when: deploy_code.stdout == "True"

    - name: Kill the butterfly process.
      shell: kill -9 butterfly_pid_stdout
      when: deploy_code.stdout == "True"

    - name: Starting butterfly.
      shell: 'nohup butterfly.server.py --unsecure --host=0.0.0.0 --port=8088 --motd=`cfy-tutorial motd` --login=False --shell="cfy-tutorial" &'
      environment:
        CONTENT_HOME: /home/ubuntu/simple-python-webserver-blueprint
        WALKTHROUGH_ROOT: /home/ubuntu/simple-python-webserver-blueprint
        NODE_VERSION: 4.2.1
        EXTERNAL_IP: "Ansible_host_external_ip"